FROM node:20-bullseye-slim

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN npm install pm2 -g

WORKDIR /usr/src/app

COPY ./dist .

RUN npm install --omit=dev

EXPOSE 1401

CMD ["npm", "run", "start"]
